-- 建立更詳細的執行記錄表
CREATE TABLE PROCEDURE_UPDATE_LOG (
    LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    PROCEDURE_NAME  VARCHAR2(100),
    EXECUTION_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS          NUMBER,          -- 0:成功, 1:失敗
    UPDATED_BY      VARCHAR2(30),
    ERROR_MESSAGE   CLOB,           -- 儲存錯誤訊息
    EXECUTION_TIME  NUMBER,         -- 執行時間（秒）
    DEBUG_INFO      CLOB,           -- 儲存除錯資訊
    CONSTRAINT PK_PROC_UPDATE_LOG PRIMARY KEY (LOG_ID)
);

-- 建立執行詳細記錄表
CREATE TABLE PROCEDURE_UPDATE_DETAIL_LOG (
    DETAIL_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    LOG_ID          NUMBER,
    STEP_NAME       VARCHAR2(100),
    STEP_STATUS     VARCHAR2(20),
    START_TIME      TIMESTAMP,
    END_TIME        TIMESTAMP,
    ELAPSED_TIME    NUMBER,
    MESSAGE         CLOB,
    CONSTRAINT PK_PROC_UPDATE_DETAIL_LOG PRIMARY KEY (DETAIL_ID),
    CONSTRAINT FK_DETAIL_LOG_MAIN FOREIGN KEY (LOG_ID) 
        REFERENCES PROCEDURE_UPDATE_LOG(LOG_ID)
);